### ISSUE TITLE
Fails with PrettyTable 0.6.0

### ISSUE THREAD

**Issue by joeshaw** [jwilder/mongodb-tools#1]
requirements.txt doesn't specify a PrettyTable version.  Current is 0.6.0.  Running fails with:

```
Traceback (most recent call last):
  File "./index_stats.py", line 120, in <module>
    main()
  File "./index_stats.py", line 70, in main
    x.set_field_align("Collection", "l")
  File "/home/joeshaw/mongodb-tools/virtualenv/lib/python2.6/site-packages/prettytable.py", line 163, in __getattr__
    raise AttributeError(name)
AttributeError: set_field_align
```

Explicitly specifying 0.5.0 works.  Didn't look into it beyond this.

**Comment by KabanguJDTshikuma** [comment]
Can you please explain what was the problem?
